USE `plantopedia`;

INSERT INTO `plants` VALUES 
('rice', 'Rice is a staple food crop of India and one of the most important cereal crops. It is grown in flooded fields called paddies. The plant grows to about 1.2 meters tall with long slender leaves and produces clusters of flowers that develop into grain. India is one of the world\'s largest producers of rice.', 'Rice grows best in clay or loamy soils with good water retention. The soil should be fertile with pH between 5.5-6.5. Puddled soil conditions are ideal for rice cultivation.', 'Rice requires abundant water, typically 15-20cm standing water in the field during the growing period. The field should be kept flooded from transplanting until about 2 weeks before harvest.', 'Apply NPK fertilizer in the ratio of 120:60:60 kg/ha. First application at transplanting, second at tillering stage, and third at panicle initiation stage.', 'Rice grows best in temperatures between 22-32°C. It requires high humidity and full sunlight for optimal growth.', 'Rice typically takes 100-150 days from planting to harvest, depending on the variety.', 'Rice is rich in carbohydrates, contains moderate amounts of protein, vitamins (especially B vitamins), and minerals. It is also a good source of fiber when consumed as brown rice.'),

('wheat', 'Wheat is one of India\'s most important food grains and is extensively cultivated in the northern plains. It is a winter crop that produces golden-colored grains used to make flour. The plant grows in clusters and can reach heights of 0.7-1.4 meters.', 'Well-drained, fertile loamy soil with pH between 6.0-7.0 is ideal for wheat cultivation. The soil should have good organic matter content and water retention capacity.', 'Wheat requires moderate water, about 450-650mm during the growing season. Critical irrigation stages are crown root initiation, tillering, flowering, and grain filling.', 'Apply balanced NPK fertilizer (120:60:40 kg/ha). First dose at sowing, second at crown root initiation, and third at pre-flowering stage.', 'Wheat grows best in cool temperatures between 15-25°C during growing stage and slightly warmer temperatures during ripening.', 'Wheat typically takes 120-150 days from sowing to harvest.', 'Wheat is rich in carbohydrates, proteins, dietary fiber, and various vitamins and minerals, particularly B vitamins, iron, and zinc.'),

('sugarcane', 'Sugarcane is a tall perennial grass and one of India\'s major commercial crops. It grows as thick, tall stalks that can reach 3-6 meters in height. The plant is primarily grown for its sweet juice, which is processed to make sugar and jaggery.', 'Deep, well-drained loamy soil rich in organic matter with pH between 6.5-7.5 is ideal. The soil should have good moisture retention capacity.', 'Sugarcane requires regular irrigation throughout its growth period. About 1500-2500mm water is needed during the entire growing season.', 'Apply NPK fertilizer in ratio of 250:75:120 kg/ha. Split application is recommended with first dose at planting, second at tillering, and third at grand growth phase.', 'Sugarcane grows best in tropical and subtropical climates with temperatures between 20-35°C. It requires high humidity and abundant sunlight.', 'Sugarcane crop typically takes 12-18 months to mature depending on the variety and growing conditions.', 'Sugarcane juice is rich in natural sugars, minerals like calcium, phosphorus, iron, and vitamins like vitamin C and B-complex vitamins.'),

('turmeric', 'Turmeric is a rhizomatous herbaceous perennial plant that is widely cultivated in India. The plant grows up to 1 meter tall with large green leaves and produces clusters of yellow flowers. The rhizomes are used as a spice and have medicinal properties.', 'Well-drained, loose, fertile loamy soil rich in organic matter with pH between 6.0-7.5 is ideal for turmeric cultivation.', 'Turmeric requires regular watering to maintain soil moisture. First irrigation immediately after planting, then at 7-10 day intervals depending on soil and weather conditions.', 'Apply organic manure (25-30 tons/ha) before planting. NPK fertilizer (25:50:60 kg/ha) should be applied in split doses.', 'Turmeric grows best in warm and humid conditions with temperatures between 20-30°C. It requires partial shade for optimal growth.', 'Turmeric takes about 7-9 months from planting to harvest.', 'Turmeric is rich in curcumin, which has anti-inflammatory and antioxidant properties. It also contains essential oils, proteins, vitamins C and B6, and minerals.'),

('cotton', 'Cotton is one of India\'s most important commercial crops. It\'s a shrubby plant that grows about 1-2 meters tall and produces white, fluffy fibers in its seeds. India is one of the world\'s largest producers of cotton.', 'Deep, well-drained black cotton soil or alluvial soil with pH between 6.0-8.0 is ideal. The soil should have good moisture retention capacity.', 'Cotton needs adequate moisture during flowering and boll formation. About 700-1300mm water is required during the growing season.', 'Apply NPK fertilizer (120:60:60 kg/ha) in split doses. First application at sowing, second at flowering, and third at boll formation stage.', 'Cotton grows best in warm climate with temperatures between 21-30°C. It requires plenty of sunshine and moderate humidity.', 'Cotton crop takes about 150-180 days from sowing to harvest.', 'While cotton is primarily grown for its fiber, cotton seeds are rich in protein and oil, and are used for animal feed and oil extraction.'); 